# Generated by Django 4.2.7 on 2023-11-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('condition_text', models.CharField(max_length=255)),
                ('icon_url', models.CharField(max_length=200)),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('avg_temp', models.FloatField()),
                ('avg_humidity', models.FloatField()),
            ],
        ),
    ]
